import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";
import { SocketProvider } from "@/components/providers/socket-provider";
import { QueryProvider } from "@/components/providers/query-provider";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nearest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        font.className,
        "bg-gray-100 dark:bg-black"
      )}>
        <div className="circlePosition absolute z-0 right-[60%] bottom-[10%] transform w-[770px] h-[210px] bg-[#2563eb] bg-opacity-30 rounded-[100%] blur-[250px]"></div>
        <div className="circlePosition absolute z-0 right-[60%] bottom-[10%] transform w-[770px] h-[210px] bg-[#2563eb] bg-opacity-30 rounded-[100%] blur-[250px]"></div>
        {/* <div className="circlePosition absolute z-0 right-[10%] top-[10%] transform w-[770px] h-[210px] bg-[#477df0] bg-opacity-30 rounded-[100%] blur-[250px]"></div> */}
        <div className="circlePosition absolute z-0 right-[10%] top-[50%] transform w-[880px] h-[210px] bg-[#477df0] bg-opacity-30 rounded-[100%] blur-[250px]"></div>
        <div className="circlePosition absolute z-0 right-[6%] top-[8%] transform w-[880px] h-[500px] bg-[#477df0] bg-opacity-30 rounded-[100%] blur-[250px]"></div>
        <ThemeProvider
        attribute="class"
        defaultTheme="white"
        enableSystem={false}
        storageKey="discord-theme">
        <SocketProvider>
          <ModalProvider />
          <QueryProvider>
            {children}
          </QueryProvider>
        </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
